Parameters:
  EcsClusterName:
    Type: String
    Description: "Specify ECS Cluster Name."
  EcsServiceName:
    Type: String
    Description: "Specify ECS Cluster Service Name."
  ContainerImage:
    Type: String
    Description: "Specify Container Image name."
  AppHostPort:   
    Type: Number
    Description: "Specify Host Port."
    Default: 80
  AppContainerPort:
    Type: Number
    Description: "Specify Container Port."
    Default: 80
  TaskExecutionArn:
    Type: String
    Description: "Specify Task Execution ARN."
  AppName:
    Type: String
    Description: "Specify Container name."
  SecurityGroupId:
    Type: String
    Description: "Specify Security group id."
  myTargetGroup:
    Type: String
    Description: "Specify Target Group id."
  subnetAId:
    Type: String
    Description: "Specify subnetA id."
  subnetBId:
    Type: String
    Description: "Specify subnetB id."


Resources:
  MyEcsCluster:
    Type: AWS::ECS::Cluster
    Properties: 
      ClusterName: !Ref EcsClusterName

  TaskDefFarget:  
    Type: AWS::ECS::TaskDefinition
    Properties:
      NetworkMode: awsvpc
      Family: !Ref EcsServiceName
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      ExecutionRoleArn: !Ref TaskExecutionArn
      ContainerDefinitions: 
        - 
          Name: !Ref AppName
          Image: !Ref ContainerImage
          Cpu: 256
          Memory: 512
          PortMappings: 
            - 
              ContainerPort: !Ref AppContainerPort
              HostPort: !Ref AppHostPort

  MyEcsService: 
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref EcsServiceName
      Cluster: !Ref MyEcsCluster
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefFarget
      NetworkConfiguration:
        AwsvpcConfiguration: 
          AssignPublicIp: DISABLED
          SecurityGroups:
           - !Ref SecurityGroupId
          Subnets:
            - !Ref subnetAId
            - !Ref subnetBId
      LoadBalancers:
        - TargetGroupArn: !Ref myTargetGroup
          ContainerPort: !Ref AppContainerPort
          ContainerName: !Ref AppName
